#!/bin/bash
echo "hello dthere my name is Shangre, I am Josh's boss!"
echo "how are you today?"
sleep 2
 echo "1) worried"
 echo "2) I thought you are Shangre?"
 echo "3) I aint falling for this crap gng."
 read ans


